agent {
    data_dir = "/run/spire/agent"
    log_level = "DEBUG"

    server_address = "192.168.2.102"
    server_port = "8081"

    trust_domain = "home-ai-lab"

    socket_path = "/var/run/spire/agent.sock"

    insecure_bootstrap = true
}

plugins {
    NodeAttestor "join_token" {
        plugin_data {}
    }

    WorkloadAttestor "docker" {
        plugin_data {
            use_new_container_locator = true
            docker_socket_path = "unix:///var/run/docker.sock"
        }
    }

    KeyManager "disk" {
        plugin_data {
            directory = "/run/spire/agent"
        }
    }
}
